name: James Yong, Software Engineer
markdown: kramdown
theme: jekyll-theme-modernist
permalink: /blog/:year/:month/:day/:title
show_downloads: false
google_analytics: UA-99990642-1
title: James's Open Source Projects

staticman:
  branch: "master"
