name: James Yong, Software Engineer
markdown: kramdown
theme: jekyll-theme-modernist
permalink: /blog/:year/:month/:day/:title
show_downloads: false
google_analytics: UA-99990642-1
title: James's Open Source Projects

staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
